ara/ota/cloud/cloud/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static
from django.views.static import serve
from django.conf.urls import url
urlpatterns = [
    path('',include('core.urls')),
    path('admin/', admin.site.urls),

    url(r'^media/(?P<path>.*)$', serve,{'document_root': settings.MEDIA_ROOT}), 
    url(r'^static/(?P<path>.*)$', serve,{'document_root': settings.STATIC_ROOT}), 
]

urlpatterns += static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL,document_root=settings.STATIC_ROOT)

ara/ota/cloud/core/urls.py
from django import views
from . import views 
from django.urls import URLPattern, path
from django.contrib.auth.views import LogoutView
from core.views import Indexview
from core.views import download_file
from core.views import meta_data_send
from core.views import *

app_name='core'
urlpatterns=[
    path('',views.login_page, name="login"),
    path('index',Indexview.as_view(),name='index'),
    path('index2',Indexview2.as_view(),name='index2'),
    path('download/<str:value>/', download_file),
    path('hash/<str:value>/', hash_file),
    path('meta_data_send', meta_data_send),
    path('logout/',views.logout_view, name="logout"),
]

ara/ota/cloud/core/models.py
from fileinput import filename
from django.db import models
import os

def file_path(instance,filename):
   path="documents/"
   format=filename
   return os.path.join(path,format)


# Create your models here.

class FileHandler(models.Model):
   file_upload=models.FileField(upload_to=file_path,blank=True, null=True)
   file_name=models.CharField(null=False,max_length=500,default='')
  # file_version=models.FloatField(default=0)

   def __str__(self) :
      return self.file_name

ara/ota/cloud/core/forms.py
from email.policy import default
from django import forms
from core.models import FileHandler

class FileHandlerform(forms.ModelForm):
    file_upload=forms.FileField(required=False)
    file_name=forms.CharField(widget=forms.TextInput(attrs={'placeholder': 'Write file name'}))

    class Meta():
        model = FileHandler
        fields =('file_upload','file_name',)

ara/ota/cloud/core/views.py
from logging import FileHandler
from multiprocessing import get_context
import re
from django.shortcuts import redirect, render
from django.template import context
from django.views.generic import TemplateView
from .models import FileHandler, file_path
from .forms import FileHandlerform
import mimetypes
from django.http import HttpResponse
import os
from django.contrib.auth import authenticate, login, logout
import hashlib

# Create your views here.s


def login_page(request):
    if request.method == "POST":
        username = request.POST.get('username')
        password = request.POST.get('password')
        user = authenticate(request, username = username, password = password)
        if user is not None:
            login(request, user)
            return redirect('core:index')
            
        else:
            # Return an 'invalid login' error message.
            return render(request, "core/login.html",{
                        "message":"wrong username or password"
                    })
    context = {}
    return render(request, "core/login.html", context)


def logout_view(request):
    logout(request)
    return redirect('core:login')



class Indexview(TemplateView):
    template_name='core/index.html'

    def get_context_data(self, **kwargs):
        context=super().get_context_data(**kwargs)
        get_files=FileHandler.objects.all()
        context={'form':FileHandlerform,'get_files':get_files}
        return context

    def post(self,request,**kwargs):
        context= {}
        if request.method == 'POST':
            form=FileHandlerform(request.POST ,request.FILES )
            if form.is_valid():
               # obj=form.save(commit=False)
               # obj.save()
                form_model = FileHandler()
                form_model.file_upolad= form.cleaned_data['file_upload']
                form_model.file_name= form.cleaned_data['file_name']
                form.save()
                print(form)
                return redirect('core:index')

            else:
                context['form']=form
        else:
            context['form']= form

        return redirect('core:index')


class Indexview2(TemplateView):
    template_name='core/index2.html'

    def get_context_data(self, **kwargs):
        context=super().get_context_data(**kwargs)
        get_files=FileHandler.objects.all()
        context={'form':FileHandlerform,'get_files':get_files}
        return context

    def post(self,request,**kwargs):
        context= {}
        if request.method == 'POST':
            form=FileHandlerform(request.POST ,request.FILES )
            if form.is_valid():
               # obj=form.save(commit=False)
               # obj.save()
                form_model = FileHandler()
                form_model.file_upolad= form.cleaned_data['file_upload']
                form_model.file_name= form.cleaned_data['file_name']
                form.save()
                print(form)
                return redirect('core:index2')

            else:
                context['form']=form
        else:
            context['form']= form

        return redirect('core:index2')




def meta_data_send(request):
    data=FileHandler.objects.all()
    print(data)
    f = open("demofile2.txt", "w")
    print("*******************")
    for x in data:
        print(x)
        f.write(str(x))
        f.write('\n')
    f.close()
    filename ="demofile2.txt"
    filepath="demofile2.txt"
    path = open(filepath, 'r')
    # Set the mime type
    mime_type, _ = mimetypes.guess_type(filepath)
    # Set the return value of the HttpResponse
    response = HttpResponse(path, content_type=mime_type)
    # Set the HTTP header for sending to browser
    response['Content-Disposition'] = "attachment; filename=%s" % filename
    # Return the response value
    return response






def download_file(request,value):
    # Define Django project base directory
    BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
    # Define text file name
    filename = value
    # Define the full file path
    filepath = BASE_DIR+'/cloud/media/documents/'+ filename
    # Open the file for reading content
    path = open(filepath, 'rb')

    # Set the mime type
    mime_type, _ = mimetypes.guess_type(filepath)
    
    
    # Set the return value of the HttpResponse
    response = HttpResponse(path, content_type=mime_type)
    
    #print(hashlib.sha256(response))
    # Set the HTTP header for sending to browser
    response['Content-Disposition'] = "attachment; filename=%s" % filename
    
    #print(hashlib.sha256(response['Content-Disposition'].encode('utf-8')).hexdigest())
    # Return the response value
    
    return response



def hash_file(request,value):
    # Define Django project base directory
    BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
    # Define text file name
    filename = value
    # Define the full file path
    filepath = BASE_DIR+'/cloud/media/documents/'+ filename
    # Open the file for reading content
    path = open(filepath, 'rb')
    
    
    h = hashlib.sha1()
    with open(filepath, 'rb') as f:
        chunk = 0
        while chunk != b'':
           # read only 1024 bytes at a time
           chunk = f.read(1024)
           h.update(chunk)
           print( h.hexdigest())
   #for line in f:
         #   hashed_line = hashlib.sha256(line.rstrip()).hexdigest()
          #  print(hashed_line)
        # loop till the end of the file
    
    
    
    #print(hashlib.sha256(response['Content-Disposition'].encode('utf-8')).hexdigest())
    # Return the response value
    
    
    return HttpResponse(h.hexdigest())

ara/ota/cloud/templates/core/index.html
{% load static %}
<!DOCTYPE html>
{% load widget_tweaks %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.5.0/css/all.css" integrity="sha384-B4dIYHKNBt8Bc12p+WXckhzcICo0wtJAoU8YZTY5qE0Id1GSseTk6S+L3BlXeVIU" crossorigin="anonymous">
    <title>django upload download</title>
</head>

<style>
    .makeitcenter {
        right: 50%;
        bottom: 50%;
        transform: translate(50%, 50%);
        position: absolute;
    }
    
    body {
      
      height: 90vh;
      background: linear-gradient(to bottom, #00ccff 0%, #99ffcc 100%);
    }
    
    .card {
        padding-left: 20px;
        padding-right: 20px;
        box-shadow: 0 0px 20px 0 rgba(12, 12, 12, 0.2);
        background-color: rgba(0, 162, 255, 0.2)!important;
        transition: 0.3s;
    }
    .navbar {
       
        opacity: 0.8; }
        #home-section {
            
            min-height: 700px; }
            #home-section .dark-overlay {
              background-color: rgba(0, 0, 0, 0.7);
              position: absolute;
              top: 0;
              left: 0;
              width: 100%;
              min-height: 700px; }
            #home-section .home-inner {
              padding-top: 150px; }
            #home-section .card-form {
              opacity: 0.8; }
            #home-section .fa {
              color: #008ed6;
              background: #fff;
              padding: 4px;
              border-radius: 5px;
              font-size: 30px; }
</style>
<body>

  <!-- NAVBAR SECTION -->
  <div>
    <nav class="navbar navbar-expand-sm bg-dark navbar-dark fixed-top">
      <div class="container">
          <a href="" class="navbar-brand">
             <h4 class="d-inline align-middle" >OTA</h4>
            </a>
        <div >
          <ul class="navbar-nav ml-auto">
            
            <a href="{% url 'core:logout' %}" class="nav-link">Logout</a>

            <a  class="btn" style="display: block; color:black;"  href="{% url 'core:index2' %}"><i class="fa fa-moon" style="font-size:25px;color:black"></i></a>

          </ul>
        </div>
      </div>
    </nav>
  </div>


  <div class="container2" style="margin-top: 70px;">
    <div class="row">
      <div class="col-lg-6">
        

          <!-- FORM SECTION -->
                  
          <div class="d-flex justify-content-center" style="margin-top: 70px;">
              <div class="card  text-center card-form ">
                  <div class="card-body">
                    <div class="row">
                      <div class="col text-center">  
                          <div class="py-5">

                          <form method="POST" enctype= "multipart/form-data">
                              {%csrf_token%}

                              <div class="form-group">
                                  {{form.file_upload | add_class:"form-control"}}
                                  <div class="py-3">
                                    {{form.file_name}}
                                    
                                </div>
                                <button type="submit" class="btn btn-primary btn-block">Save</button>
                          </form>
                          <div class="py-3">


                          <url>
                              
                              {%for item in get_files%}
                              <div class="border border-dark rounded" style="margin:5px">
                              
                                  
                                <a class="text-dark" href="{{item.file_upload.url}}" download>{{item.file_name}} </a>
                              
                              
                          </div>

                              {%endfor%}
                              
                          </url>
                      </div>
                    </div>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
          
      <div class="col-lg-6 d-none d-lg-block" >
        
        <img src="{% static 'img/car_cloud_.png' %}"  width="700" height="600">
      </div>
     
    </div>
  </div>


</body>

</html>

ara/ota/cloud/templates/core/index2.html
{% load static %}
<!DOCTYPE html>
{% load widget_tweaks %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.5.0/css/all.css" integrity="sha384-B4dIYHKNBt8Bc12p+WXckhzcICo0wtJAoU8YZTY5qE0Id1GSseTk6S+L3BlXeVIU" crossorigin="anonymous">
    <title>django upload download</title>
</head>

<style>
    .makeitcenter {
        right: 50%;
        bottom: 50%;
        transform: translate(50%, 50%);
        position: absolute;
    }
    
    body {
      height: 90vh;
      background-image: url("{% static 'img/dark_.jpg' %}") ;
      background-size: cover;
      background-repeat: no-repeat;
      /*background-color: black !important;*/
    }
    
    .card {
        padding-left: 20px;
        padding-right: 20px;
        box-shadow: 0 0px 20px 0 rgba(12, 12, 12, 0.2);
        background-color:#76B947 !important;
        transition: 0.3s;
    }
    .navbar {
        opacity: 0.8; }
        #home-section {
            
            min-height: 700px; }
            #home-section .dark-overlay {
              background-color: rgba(0, 0, 0, 0.7);
              position: absolute;
              top: 0;
              left: 0;
              width: 100%;
              min-height: 700px; }
            #home-section .home-inner {
              padding-top: 150px; }
            #home-section .card-form {
              opacity: 0.8; }
            #home-section .fa {
              color: #046ef0;
              background: #fff;
              padding: 4px;
              border-radius: 5px;
              font-size: 30px; }
</style>
<body>

  <!-- NAVBAR SECTION -->
  <div>
    <nav class="navbar navbar-expand-sm bg-white  fixed-top">
      <div class="container">
          <a href="" class="navbar-brand">
             <h4 class="d-inline align-middle" style="color: #4b0082">OTA</h4>
            </a>
        <div >
          <ul class="navbar-nav ml-auto">
            
            <a href="{% url 'core:logout' %}" class=" nav-link" style="color: #4b0082">Logout</a>

            <a class="btn" style="display: block;  color:black" href="{% url 'core:index' %}"><i class="fas fa-sun fa-lg" style="font-size:25px;color:#4b0082"></i></a>

          </ul>
        </div>
      </div>
    </nav>
  </div>

  <div class="container2" style="margin-top: 70px;">
    <div class="row">
      <div class="col-lg-6">
        

          <!-- FORM SECTION -->
                  
          <div class="d-flex justify-content-center" style="margin-top: 70px;">
              <div class="card  text-center card-form ">
                  <div class="card-body">
                    <div class="row">
                      <div class="col text-center">  
                          <div class="py-5">

                          <form method="POST" enctype= "multipart/form-data">
                              {%csrf_token%}

                              <div class="form-group">
                                  {{form.file_upload | add_class:"form-control"}}
                                  <div class="py-3">
                                    
                                    {{form.file_name}}
                                    
                                </div>
                                <button type="submit" class="btn btn-primary btn-block">Save</button>
                          </form>
                          <div class="py-3">


                          <url>
                              
                              {%for item in get_files%}
                              <div class="border  border-dark rounded " style="margin:5px">
                              
                                  
                                <a class="text-dark" href="{{item.file_upload.url}}" download>{{item.file_name}} </a>
                              
                              
                          </div>

                              {%endfor%}
                              
                          </url>
                      </div>
                    </div>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
          

          
          


      
      <div class="col-lg-6 d-none d-lg-block" >
        
        <img src="{% static 'img/car_cloud_.png' %}"  width="700" height="600">
      </div>
     
    </div>
  </div>



</body>
</html>

ara/ota/cloud/templates/core/login.html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <meta http-equiv="X-UA-Compatible" content="ie=edge">
  <title>Face Attendencs</title> 
  <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">

</head>
<style>
    .makeitcenter {
        right: 50%;
        bottom: 50%;
        transform: translate(50%, 50%);
        position: absolute;
    }
    
    body {
        background-color: rgb(166, 166, 221, 0.2) !important;
    }
    
    .card {
        padding-left: 20px;
        padding-right: 20px;
        box-shadow: 0 0px 20px 0 rgba(12, 12, 12, 0.2);
        background-color: rgba(0, 162, 255, 0.2)!important;
        transition: 0.3s;
    }
</style>






<body >
   
        
<div class="makeitcenter">
    <div class="card  text-center card-form ">
        <div class="card-body">
      <div class="row">
        <div class="col text-center">  
          <div class="py-5">
            {% if message %}
            <div class="alert alert-danger" role="alert">
                {{ message.capitalize }}
            </div>
            {% endif %}
            
            <form  style="text-align :center "   method="POST" style="width:70% ">
                    
                    
                    {% csrf_token %}
                  
           
            <div class="row">
        
            <div class="col-lg-3"> </div>
            <div class="col-lg-12">
                <label for="fname"><strong>User name</strong></label><br>
                <input type="text"id='input username' name='username' class="username"  placeholder="username"><br>
            </div>
        </div>
        <div class="py-3">
        
            <div class="row">
                <div class="col-lg-3"> </div>
                <div class="col-lg-12">
                    <label for="fname"><strong>Password</strong></label><br>
                    <input type="password" id='input password' name='password' class="password" placeholder="Password"><br>
                </div>
            </div>
        </div>
       
       

        <div class="py-5">
            <div class="col-lg-12">
                <input   class="btn btn-outline-primary btn-block" value="login" type="submit"> 
                </div>
                
    </form>
    
    







</div>
</div>


        
           
            


    </body>
    </html>       